14_authentication/config/routes.rb
Ritly::Application.routes.draw do
  resources :users, :sessions

  get "sessions/new"
  get "sessions/destroy"
  get "/sign_up", to: 'users#new'
  get "/users/:id", to: 'users#show'

  root to: 'rits#index'
  
  get '/rits', to: 'rits#index'
  
  post '/rits', to: 'rits#create'

  get '/go/:code', to: 'rits#visited'

  get '/preview/:code/', to: 'rits#preview'

  post '/update', to: 'rits#update'

 end

14_authentication/app/models/rit.rb
# == Schema Information
#
# Table name: rits
#
#  id         :integer          not null, primary key
#  code       :string(25)
#  link       :string(255)
#  visits     :integer          default(0)
#  created_at :datetime
#  updated_at :datetime
#

class Rit < ActiveRecord::Base
	
	validates :link, presence: { message: "Where's your link? It's empty!"}
	
	validates :code, format: { with: /\A[a-zA-Z0-9_.-]+\z/,
    message: "Your link only takes letters, numbers, and dashes."}
	validates :code, uniqueness: { message: "That link's been taken already."}
	validates :code, length: { maximum: 25, message: "Your link's too long. 25 characters only, please." }
	validates :code, presence: { message: "Where's your link? It's empty!"}

	def self.make_code
		looping = true
		while looping
			code = SecureRandom.urlsafe_base64(5)	
			looping = false if find_by(code: code) == nil
		end
		code
	end

	def start_with_http
		self.link = "http://#{link}" if URI(self.link).scheme == nil
		self.save
	end

end

14_authentication/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  #validations on sign up form
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 	presence:   true,
                    	format:     { with: VALID_EMAIL_REGEX },
                    	uniqueness: { case_sensitive: false }
  validates :password,	presence: true, length: { minimum: 6 },
                    	confirmation: true
  validates :password_confirmation, presence: true

  #creates password_digest
  has_secure_password

  def create_remember_token
 	self.remember_token = SecureRandom.urlsafe_base64
  end


end

14_authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception
end

14_authentication/app/controllers/rits_controller.rb
class RitsController < ApplicationController

	def index
		@rits = Rit.last(5).reverse
	end

	def preview
		code = params[:code]
		@rit = Rit.find_by(code: code)
	end

	def visited

		code = params[:code]
		rit = Rit.find_by(code: code)
		Rit.increment_counter(:visits, rit.id)

		redirect_to rit.link

	end

	def create

	    rit_attributes = rit_link_param
		rit_attributes[:code] = Rit.make_code
		@rit = Rit.create(rit_attributes)

		if @rit.errors.any?
			flash[:notice] = @rit.message
			@rits = Rit.last(5).reverse 
			render :index
		else
			@rit.start_with_http
			redirect_to "/preview/#{@rit.code}"
		end
	end

	def update
		rit_attributes = rit_params
		@rit = Rit.find(rit_attributes[:id])
		@rit.code = rit_attributes[:code]
		@rit.save

		redirect_to (@rit.errors.any? ? :back : "/preview/#{rit.code}")
	end


  private
	  def rit_link_param
	  	#raise params.inspect
	    params[:rit].permit(:link)
	  end

	  def rit_params
	  	
	    params[:rit].permit(:id, :code)
	  end
end

14_authentication/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
  end
end

14_authentication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new()
  	render :sign_up
  end
  
  def create
  	@user = User.new(user_params)

  	if @user.save
  		#sign_in @user
  		redirect_to @user
  	else
  		render :sign_up
  	end

  end
  def show
  	@user = User.find(params[:id])
  	render :profile
  end

  def update
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

14_authentication/app/helpers/rits_helper.rb
module RitsHelper
end

14_authentication/app/helpers/sessions_helper.rb
module SessionsHelper
# SessionHelper manages @current_user, that's the user currently
  # signed in.

  # signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

14_authentication/app/helpers/users_helper.rb
module UsersHelper
end

14_authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:100,400&text=Ritly' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

14_authentication/app/views/rits/_customize_modal.html.erb
<!-- check whether string is valid: 
  1) (A-Z, a-z, 0-9, “-” and “_”. “=”) 
  2) unique
  3) less than 25 characters
  4) exists
Return error if not --> 

<div class="modal fade" id="myModal">
  <%= form_for :rit, :url => {:action => "update"}, class: 'form-horizontal', role: 'form' do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Customize</h4>
      </div>
      <div class="modal-body">
            <p class="domain-url">http://localhost:3000/go/</p>
            <%= f.text_field :code, placeholder: "Paste your URL here", onclick:'this.select();', value: @rit.code, class: 'form-control input-lg', id: "custom-box", tabindex: 1, size: 25 %>
            <%= f.hidden_field :id, value: @rit.id %>
            <br>
            <br>
            <% if !@rit.nil? && @rit.errors.any? %>
              <div id="code-error" class="error-alert">
                <h2 class="alert-headline">Woops! <%= pluralize(@rit.errors.count, "error") %>:</h2>
             
                <ul class="alert-bullets">
                <% @rit.errors[:code].each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
       
      </div>    
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
   <% end %>
</div><!-- /.modal -->

14_authentication/app/views/rits/_history.html.erb
<div class="recent-rits">
	<h3 class="table-headline"><%= headline %></h3>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>URL</th>
				<th>Short link</th>
				<th>Visits</th>
				<th>Created</th>
			</tr>
		</thead>
		<tbody>
		<% @rits.each do |r| %>
			<tr>
				<td><%= r.link.truncate(40) %></td>
				<td><%=link_to "http://localhost:3000/go/#{r.code}", "http://localhost:3000/preview/#{r.code}" %></td>
				<td><%= r.visits %></td>
				<td><%= r.created_at.to_formatted_s(:short) %></td> 
			</tr>	
		<% end %>
		</tbody>
	</table>
</div>

14_authentication/app/views/rits/_logo.html.erb
<h1 class="logo preview-logo"><a class="home-link" href="/">Ritly<br>
:)</a></h1>
<p class="sign-in">
	<%= link_to "Sign up", '/sign_up', class: 'login-link'%>
	&nbsp | &nbsp
	<%= link_to "Log in", '/sessions/login', class: 'login-link'%>
</p>

14_authentication/app/views/rits/_shorten_form.html.erb
<!-- check whether string is valid url/use Noah's code return error if not:
1) exists
2) has a "." in it
3) the right characters-->

<div class="container">
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<%= form_for :rit, url: rits_path, class: 'form-horizontal', role: 'form' do |f| %>
				 <div class="col-lg-11 col-sm-10 col-xs-9 no-pad">
					<%= f.text_field :link, placeholder: "Paste your URL here", onclick:'this.select();', value: initial_text, class: 'form-control input-lg', id: 'shorten-field', tabindex: 1 %>
				</div> 
				<div class="col-lg-1 col-sm-2 col-xs-3 no-pad">
					<%= submit_tag("Shrink", class: 'btn btn-default btn-danger', id: "shorten-button") %>
				</div>
		<% end %>
		
	</nav>
</div>

14_authentication/app/views/rits/create.html.erb
Hi world

14_authentication/app/views/rits/index.html.erb
<%= render partial: 'shorten_form', locals: {initial_text: ""} %>
<h1 class="logo front-logo lower-for-nav">
	Ritly<br>
	:)</h1>
	<p class="sign-in">
		<%= link_to "Sign up", '/sign_up', class: 'login-link'%>
		&nbsp | &nbsp
		<%= link_to "Log in", '/sessions/login', class: 'login-link'%>
	</p>
<%= render partial: 'history', locals: {headline: "Recent shrinks"} %>

14_authentication/app/views/rits/preview.html.erb
<%= render partial: "shorten_form", locals: {initial_text: @rit.link} %>
<%= render 'logo' %>

<div class="container">
	<div class="row result-row">
		<div class="col-md-2 col-xs-2">
			<p class="side">Shrunk link</p>
		</div>
		<div class="col-md-6 col-xs-10">
			<%= text_field_tag('short-box', "http://localhost:3000/go/#{@rit.code}", onclick: "this.select();", class: "form-control input-lg", id: "short-box") %>
			<button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">
  				Edit this URL
			</button>
			
			<%= render 'customize_modal' %>
		</div>
	</div>
	<div class="row result-row">
		<div class="col-md-2 col-xs-2">
			<p class="side">Visits</p>
		</div>
		<div class="col-md-6 col-xs-10">
		 	<p class="visits"><%= @rit.visits %></p>
		</div>	
	</div>
	<div class="row result-row">
		<div class="col-md-2 col-xs-2">
			<p class="side">URL</p>
		</div>
		<div class="col-md-6 col-xs-10">
		 	<p class="visits"><%= @rit.link %></p>
		</div>	
	</div>
	<div class="row result-row">
		<div class="col-md-2 col-xs-2">
			<p class="side">Preview</p>
		</div>
		<div class="col-md-6 col-xs-10 side-body">
			<iframe src="<%= @rit.link %>" scrolling="no" id="peek">
		</div>
	</div>
</div>

14_authentication/app/views/users/_errors.html.erb
<% if !ele.nil? && ele.errors.any? %>
	<div id="url-error" class="error-alert">
	    <h2 class="alert-headline">Woops! <%= pluralize(ele.errors.count, "error") %>:</h2>
	    <ul class="alert-bullets">
	    <% ele.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
    	<% end %>
    	</ul>
  	</div>
<% end %>

14_authentication/app/views/users/profile.html.erb
<div class="container">
	<h1>Welcome, <%= @user.name %></h1>

<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
</div>

14_authentication/app/views/users/sign_up.html.erb
<div class="container">
	<h1>Create your Ritly account</h1>
	<div class="row">
	<%= form_for @user do |f| %>
		<%= render partial: 'errors', locals: { ele: @user } %>
		<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
		<%= f.text_field :email, placeholder: "Email", class: "form-control" %>
		<%= f.text_field :password, type: "password", placeholder: "Password", class: "form-control" %>
		<%= f.text_field :password_confirmation, type: "password", placeholder: "Confirm your password", class: "form-control" %>
		<%= f.submit("Sign up!", class: "btn btn-primary btn-lg") %>
	<% end %>
	</div>
</div>

14_authentication/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>